/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
import javax.swing.*;
import javax.swing.event.*;
import java.util.regex.*;
import java.io.*;

public class FormPenghitungKata extends javax.swing.JFrame {

    /**
     * Creates new form FormPenghitungKata
     */
    public FormPenghitungKata() {
        initComponents();
        //jika di off kan maka button hitung berfungsi dan jika di nyalakan maka akan menghitung otomatis
        txtInput.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            hitungSemua();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            hitungSemua();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            hitungSemua();
        }
    });
    }
     // DocumentListener untuk perhitungan real-time
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJudul = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblMasukkanKata = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInput = new javax.swing.JTextArea();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        PanelHasil = new javax.swing.JPanel();
        lblJudulPerhitungan = new javax.swing.JLabel();
        lblJumlahKata = new javax.swing.JLabel();
        lblJumlahKarakter = new javax.swing.JLabel();
        lblJumlahKalimat = new javax.swing.JLabel();
        lblJumlahParagraf = new javax.swing.JLabel();
        lblKata = new javax.swing.JLabel();
        lblKarakter = new javax.swing.JLabel();
        lblKalimat = new javax.swing.JLabel();
        lblParagraf = new javax.swing.JLabel();
        PanelPencarian = new javax.swing.JPanel();
        lblJudulPencarian = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        lblHasilCari = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelJudul.setBackground(new java.awt.Color(0, 153, 153));
        PanelJudul.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("APLIKASI PERHITUNGAN KATA");

        javax.swing.GroupLayout PanelJudulLayout = new javax.swing.GroupLayout(PanelJudul);
        PanelJudul.setLayout(PanelJudulLayout);
        PanelJudulLayout.setHorizontalGroup(
            PanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJudulLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelJudulLayout.setVerticalGroup(
            PanelJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJudulLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(32, 32, 32))
        );

        lblMasukkanKata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMasukkanKata.setText("Masukkan Kata :");

        txtInput.setColumns(20);
        txtInput.setRows(10);
        jScrollPane1.setViewportView(txtInput);

        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        PanelHasil.setBackground(new java.awt.Color(0, 102, 102));
        PanelHasil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblJudulPerhitungan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudulPerhitungan.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulPerhitungan.setText("HASIL PERHITUNGAN");

        lblJumlahKata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahKata.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahKata.setText("Jumlah Kata :");

        lblJumlahKarakter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahKarakter.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahKarakter.setText("Jumlah Karakter :");

        lblJumlahKalimat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahKalimat.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahKalimat.setText("Jumlah Kalimat :");

        lblJumlahParagraf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlahParagraf.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahParagraf.setText("Jumlah Paragraf :");

        lblKata.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKata.setForeground(new java.awt.Color(255, 255, 255));
        lblKata.setText("[ 0 ]");

        lblKarakter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKarakter.setForeground(new java.awt.Color(255, 255, 255));
        lblKarakter.setText("[ 0 ]");

        lblKalimat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKalimat.setForeground(new java.awt.Color(255, 255, 255));
        lblKalimat.setText("[ 0 ]");

        lblParagraf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblParagraf.setForeground(new java.awt.Color(255, 255, 255));
        lblParagraf.setText("[ 0 ]");

        javax.swing.GroupLayout PanelHasilLayout = new javax.swing.GroupLayout(PanelHasil);
        PanelHasil.setLayout(PanelHasilLayout);
        PanelHasilLayout.setHorizontalGroup(
            PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHasilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblJumlahKarakter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJumlahKalimat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJumlahParagraf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJumlahKata, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216)
                .addGroup(PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKarakter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKalimat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblParagraf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHasilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudulPerhitungan)
                .addGap(115, 115, 115))
        );
        PanelHasilLayout.setVerticalGroup(
            PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHasilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPerhitungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahKata)
                    .addComponent(lblKata))
                .addGap(18, 18, 18)
                .addGroup(PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahKarakter)
                    .addComponent(lblKarakter))
                .addGap(18, 18, 18)
                .addGroup(PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahKalimat)
                    .addComponent(lblKalimat))
                .addGap(18, 18, 18)
                .addGroup(PanelHasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahParagraf)
                    .addComponent(lblParagraf))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        PanelPencarian.setBackground(new java.awt.Color(0, 102, 102));
        PanelPencarian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblJudulPencarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudulPencarian.setForeground(new java.awt.Color(255, 255, 255));
        lblJudulPencarian.setText("PENCARIAN KATA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cari Kata :");

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        lblHasilCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHasilCari.setForeground(new java.awt.Color(255, 255, 255));
        lblHasilCari.setText("Cari : [ - ]");

        javax.swing.GroupLayout PanelPencarianLayout = new javax.swing.GroupLayout(PanelPencarian);
        PanelPencarian.setLayout(PanelPencarianLayout);
        PanelPencarianLayout.setHorizontalGroup(
            PanelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPencarianLayout.createSequentialGroup()
                        .addComponent(lblHasilCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPencarianLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudulPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        PanelPencarianLayout.setVerticalGroup(
            PanelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPencarianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudulPencarian)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHasilCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMasukkanKata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(PanelPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMasukkanKata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        hitungSemua();
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    txtInput.setText("");
    txtCari.setText("");
    lblKata.setText("0");
    lblKarakter.setText("0");
    lblKalimat.setText("0");
    lblParagraf.setText("0");
    lblHasilCari.setText("-");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        cariKata();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanKeFile();
    }//GEN-LAST:event_btnSimpanActionPerformed

    // Method untuk menghitung semua
private void hitungSemua() {
    String teks = txtInput.getText();
    
    // Hitung karakter
    int jumlahKarakter = teks.length();
    lblKarakter.setText(String.valueOf(jumlahKarakter));
    
    // Hitung kata menggunakan regex
    int jumlahKata = 0;
    if (!teks.trim().isEmpty()) {
        String[] kata = teks.trim().split("\\s+");
        jumlahKata = kata.length;
    }
    lblKata.setText(String.valueOf(jumlahKata));
    
    // Hitung kalimat menggunakan regex
    int jumlahKalimat = 0;
    if (!teks.trim().isEmpty()) {
        String[] kalimat = teks.split("[.!?]+");
        jumlahKalimat = kalimat.length;
        // Kurangi 1 jika teks diakhiri dengan tanda baca
        if (teks.trim().endsWith(".") || teks.trim().endsWith("!") || teks.trim().endsWith("?")) {
            // Sudah benar
        } else if (kalimat[kalimat.length - 1].trim().isEmpty()) {
            jumlahKalimat--;
        }
    }
    lblKalimat.setText(String.valueOf(jumlahKalimat));
    
    // Hitung paragraf
    int jumlahParagraf = 0;
    if (!teks.trim().isEmpty()) {
        String[] paragraf = teks.split("\n\n+");
        jumlahParagraf = paragraf.length;
    }
    lblParagraf.setText(String.valueOf(jumlahParagraf));
}

// Method untuk mencari kata
private void cariKata() {
    String teks = txtInput.getText();
    String kataCari = txtCari.getText().trim();
    
    if (kataCari.isEmpty()) {
        lblHasilCari.setText("Masukkan kata yang ingin dicari!");
        return;
    }
    
    // Menggunakan regex untuk mencari kata (case-insensitive)
    java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(
        "\\b" + java.util.regex.Pattern.quote(kataCari) + "\\b",
        java.util.regex.Pattern.CASE_INSENSITIVE
    );
    java.util.regex.Matcher matcher = pattern.matcher(teks);
    
    int count = 0;
    while (matcher.find()) {
        count++;
    }
    
    if (count > 0) {
        lblHasilCari.setText("Ditemukan " + count + " kali");
    } else {
        lblHasilCari.setText("Tidak ditemukan");
    }
}

// Method untuk menyimpan ke file
private void simpanKeFile() {
    try {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Simpan Hasil");
        
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            
            // Tambahkan ekstensi .txt jika belum ada
            if (!fileToSave.getAbsolutePath().endsWith(".txt")) {
                fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".txt");
            }
            
            java.io.FileWriter writer = new java.io.FileWriter(fileToSave);
            
            // Tulis teks
            writer.write("===== TEKS =====\n");
            writer.write(txtInput.getText());
            writer.write("\n\n===== HASIL PERHITUNGAN =====\n");
            writer.write("Jumlah Kata: " + lblKata.getText() + "\n");
            writer.write("Jumlah Karakter: " + lblKarakter.getText() + "\n");
            writer.write("Jumlah Kalimat: " + lblKalimat.getText() + "\n");
            writer.write("Jumlah Paragraf: " + lblParagraf.getText() + "\n");
            
            writer.close();
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "File berhasil disimpan!", 
                "Sukses", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Gagal menyimpan file: " + e.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenghitungKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHasil;
    private javax.swing.JPanel PanelJudul;
    private javax.swing.JPanel PanelPencarian;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHasilCari;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudulPencarian;
    private javax.swing.JLabel lblJudulPerhitungan;
    private javax.swing.JLabel lblJumlahKalimat;
    private javax.swing.JLabel lblJumlahKarakter;
    private javax.swing.JLabel lblJumlahKata;
    private javax.swing.JLabel lblJumlahParagraf;
    private javax.swing.JLabel lblKalimat;
    private javax.swing.JLabel lblKarakter;
    private javax.swing.JLabel lblKata;
    private javax.swing.JLabel lblMasukkanKata;
    private javax.swing.JLabel lblParagraf;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtInput;
    // End of variables declaration//GEN-END:variables
}
